Repository myakove/pr-workflows, pull requests merged in 2021-08, with the labels that each got.

#3 .
  .github/workflows/add_reviewers.yml
  .github/workflows/size_labels.yml
  .github/workflows/verified_label.yml
  main.py
Labels: Size/M

#4 .......
  .github/workflows/add_reviewers.yml
  .github/workflows/labels_by_user_input.yml
  .github/workflows/size_labels.yml
  a
  main.py
Labels: Size/XS

#5 test5
  a
  main.py
Labels: Size/XS

#7 test7
  a
  main.py
Labels: Size/XS

#8 test8
  .github/workflows/add_reviewers.yml
  .github/workflows/pr_actions.yml
  .github/workflows/size_labels.yml
Labels: Size/XS

#10 test10
  .github/workflows/pr_actions.yml
  action.yml
  main.py
Labels: Size/XS

#16 order code
  .github/workflows/code-check.yml
  .github/workflows/issue-comment.yml
  .github/workflows/pr-actions.yml
  .isort.cfg
  Dockerfile
  main.py
  pyproject.toml
  src/__init__.py
  src/add_reviewers.py
  src/labels_by_user_input.py
  src/size_label_prs.py
  src/utils.py
Labels: Size/M, Verified

#18 Fix for offensive_lang
  src/block_offensive_lanague.py
Labels: Size/XS

#24 Block merge if "Verified" label is missing
  main.py
  src/block_merge.py
  src/constants.py
  src/labels_by_user_input.py
  src/utils.py
Labels: Size/S

#23 Add XXL size label
  src/size_label_prs.py
Labels: Size/XS, Verified

#31 Only maintainers should be able to approve PRs
  main.py
  src/labels_by_user_input.py
  src/utils.py
Labels: Size/XS, Verified, Approve
